### PR TITLE
Fix proprestore not setting angular velocity back

### PR DESCRIPTION
**Pull request by wrefgtzweve**

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
Haven't tested it yet, but looks good to go. It's sadly annoyingly hard to test but i can try soon

**Comment by wrefgtzweve** [comment]
Tested and works fine

**Review by sarahsturgeon — COMMENTED** [review]
I was thinking about this and worried a bit about the _efficiency_.

I thought that maybe we could rework how we store/restore these entity properties.
I imagine there's going to be one or two other things we need to save and restore later, so I played around with a different idea that should keep it quick and extensible.

What do you think about this? Instead of storing the values, accessing them later, doing more IsValid checks, etc. - we could just create some new functions that use the scoped values while saving it, and then run those functions later, ignoring any errors that pop up.

```lua
local IsValid = IsValid
local rawget = rawget
local rawset = rawset
local pcall = pcall
local noop = function()end

local function getEntityRestorers( ents )
    local restorers = {}
    local entCount = #ents

    for i = 1, entCount do
        local ent = rawget( ents, i )

        if IsValid( ent ) then
            local physObj = ent:GetPhysicsObject()
            physObj = IsValid( physObj ) and physObj

            local velocity, angRot

            if physObj then
                velocity = physObj:GetVelocity()
                angVelocity = physObj:GetAngleVelocity()
            end

            rawset( properties, i, function()
                physObj:SetVelocity( velocity )
                physObj:SetAngleVelocity( angVelocity )
            end )
        else
            rawset( properties, i, noop )
        end
    end

    return restorers
end

local function runRestorers( restorers )
    local restorerCount = #restorers

    for i = 1, restorerCount do
        pcall( rawget( restorers, i ) )
    end
end
```

**Comment by wrefgtzweve** [comment]
Clever way of doing it, do you think it's faster though?

**Comment by sarahsturgeon** [comment]
Creating new functions does come with some overhead, but I think with the more efficient loops and fewer validity checks, my proposed way will come out on top.

**Comment by wrefgtzweve** [comment]
Tried the code you gave, it didn't work right off the bat

**Comment by wrefgtzweve** [comment]
found the issue, `rawset( properties` and `return restorers`

**Comment by wrefgtzweve** [comment]
Should be ready

**Pull request merged**
